import java.nio.*;
import java.nio.file.*;
import java.util.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import org.lwjgl.BufferUtils;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.opengl.GL;
import static org.lwjgl.opengl.GL33C.*;
import static org.lwjgl.util.shaderc.Shaderc.*;

// Requires CurrentShaderMatrix.java (the same ShaderC/SPVC options as Minecraft).
// A hidden GL raster check, not Minecraft gameplay or an FPS benchmark.
public class WindowsRasterCheck {
 static final int W=512,H=512;static int colorTarget,depthTarget,fbo; static boolean armor; static List<Integer> ubos=new ArrayList<>();
 static int program(String vs,String fs)throws Exception {int v=CurrentShaderMatrix.driverShader(GL_VERTEX_SHADER,vs),f=CurrentShaderMatrix.driverShader(GL_FRAGMENT_SHADER,fs),p=glCreateProgram();glAttachShader(p,v);glAttachShader(p,f);glLinkProgram(p);if(glGetProgrami(p,GL_LINK_STATUS)==0)throw new Exception(glGetProgramInfoLog(p));glDeleteShader(v);glDeleteShader(f);return p;}
 static String translated(Path file,int stage)throws Exception {long c=shaderc_compiler_initialize(),o=shaderc_compile_options_initialize();shaderc_compile_options_set_target_env(o,shaderc_target_env_vulkan,shaderc_env_version_vulkan_1_2);shaderc_compile_options_set_auto_bind_uniforms(o,true);shaderc_compile_options_set_preserve_bindings(o,false);shaderc_compile_options_set_generate_debug_info(o);shaderc_compile_options_set_optimization_level(o,shaderc_optimization_level_zero);shaderc_compile_options_add_macro_definition(o,"RENDERPEARL_INSTANCE_INDEX_INCLUDES_BASE_INSTANCE","");long r=shaderc_compile_into_spv(c,Files.readString(file),stage,file.toString(),"main",o);try {if(shaderc_result_get_compilation_status(r)!=shaderc_compilation_status_success)throw new Exception(shaderc_result_get_error_message(r));String s=CurrentShaderMatrix.translate(shaderc_result_get_bytes(r));Files.writeString(Path.of(file+".glsl"),s);return s;}finally{shaderc_result_release(r);shaderc_compile_options_release(o);shaderc_compiler_release(c);}}
 static float[] ident(){return new float[]{1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};}
 static float[] projection(){float f=1.6f,n=.05f,far=100;float sign=armor?1:-1;return new float[]{f,0,0,0,0,f,0,0,0,0,sign*(far+n)/(far-n),-1,0,0,sign*2*far*n/(far-n),0};}
 static void block(int p,String name,int binding,float[] values){int index=glGetUniformBlockIndex(p,name);if(index==GL_INVALID_INDEX)return;int size=glGetActiveUniformBlocki(p,index,GL_UNIFORM_BLOCK_DATA_SIZE);ByteBuffer b=BufferUtils.createByteBuffer(size);b.asFloatBuffer().put(values,0,Math.min(values.length,size/4));int u=glGenBuffers();ubos.add(u);glBindBuffer(GL_UNIFORM_BUFFER,u);glBufferData(GL_UNIFORM_BUFFER,b,GL_STATIC_DRAW);glBindBufferBase(GL_UNIFORM_BUFFER,binding,u);glUniformBlockBinding(p,index,binding);}
 static void uniforms(int p,float time){glUseProgram(p);float[] mv=ident();mv[14]=-3;float[] dynamic=new float[40];System.arraycopy(mv,0,dynamic,0,16);System.arraycopy(ident(),0,dynamic,16,16);Arrays.fill(dynamic,32,36,1);block(p,"DynamicTransforms",0,dynamic);block(p,"Projection",1,projection());block(p,"Lighting",2,new float[]{0,1,0,0,0,0,1,0});block(p,"Fog",3,new float[]{0,0,0,0,100,200,100,200,200,200,0,0});block(p,"Globals",4,new float[]{0,0,0,0,0,0,0,time/24000,W,H,0,0});for(int i=0;i<3;i++){int u=glGetUniformLocation(p,"Sampler"+i);if(u>=0)glUniform1i(u,i);}}
 static int texture(Path file,int w,int h)throws Exception{byte[] bytes=Files.readAllBytes(file);ByteBuffer b=BufferUtils.createByteBuffer(bytes.length).put(bytes);b.flip();int t=glGenTextures();glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,t);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,b);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);return t;}
 static int[] geometry(Path file,int count,int base,int stride)throws Exception{byte[] bytes=Files.readAllBytes(file);ByteBuffer b=BufferUtils.createByteBuffer(bytes.length+base*stride*4);b.position(base*stride*4).put(bytes).flip();int vao=glGenVertexArrays(),v=glGenBuffers(),e=glGenBuffers();glBindVertexArray(vao);glBindBuffer(GL_ARRAY_BUFFER,v);glBufferData(GL_ARRAY_BUFFER,b,GL_STATIC_DRAW);glEnableVertexAttribArray(0);glVertexAttribPointer(0,3,GL_FLOAT,false,stride*4,0L);glEnableVertexAttribArray(2);glVertexAttribPointer(2,2,GL_FLOAT,false,stride*4,12L);glVertexAttrib4f(1,1,1,1,1);glVertexAttribI2i(3,0,0);glVertexAttribI2i(4,240,240);glVertexAttrib3f(6,0,0,-1);if(stride==8){glEnableVertexAttribArray(5);glVertexAttribPointer(5,3,GL_FLOAT,false,32,20L);}IntBuffer indices=BufferUtils.createIntBuffer(count/4*6);for(int i=0;i<count;i+=4)indices.put(new int[]{base+i,base+i+1,base+i+2,base+i+2,base+i+3,base+i});indices.flip();glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,e);glBufferData(GL_ELEMENT_ARRAY_BUFFER,indices,GL_STATIC_DRAW);return new int[]{vao,v,e,count/4*6};}
 static byte[] draw(int p,int texture,int[] mesh){glUseProgram(p);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,texture);glBindVertexArray(mesh[0]);glClearColor(0,0,0,0);glClearDepth(armor?0:1);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);glDrawElements(GL_TRIANGLES,mesh[3],GL_UNSIGNED_INT,0L);ByteBuffer b=BufferUtils.createByteBuffer(W*H*4);glReadPixels(0,0,W,H,GL_RGBA,GL_UNSIGNED_BYTE,b);byte[] result=new byte[b.remaining()];b.get(result);int err=glGetError();if(err!=0)throw new IllegalStateException("GL error "+err);return result;}
 static void png(Path path,byte[] rgba)throws Exception {BufferedImage im=new BufferedImage(W,H,BufferedImage.TYPE_INT_ARGB);for(int y=0;y<H;y++)for(int x=0;x<W;x++){int i=(y*W+x)*4;im.setRGB(x,H-1-y,((rgba[i+3]&255)<<24)|((rgba[i]&255)<<16)|((rgba[i+1]&255)<<8)|(rgba[i+2]&255));}ImageIO.write(im,"png",path.toFile());}
 public static void main(String[] args)throws Exception{
  Path root=Path.of(args[0]);armor=Files.exists(root.resolve("baseline.vert"));if(!GLFW.glfwInit())throw new Exception("GLFW init");GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE,GLFW.GLFW_FALSE);GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MAJOR,armor?4:3);GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MINOR,armor?6:3);GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_PROFILE,GLFW.GLFW_OPENGL_CORE_PROFILE);long win=GLFW.glfwCreateWindow(W,H,"obj3 raster check",0,0);if(win==0)throw new Exception("GLFW window");GLFW.glfwMakeContextCurrent(win);GL.createCapabilities();System.out.println("GPU "+glGetString(GL_RENDERER)+" | "+glGetString(GL_VERSION));
  int direct=program(translated(root.resolve("shader.vert"),shaderc_vertex_shader),translated(root.resolve("shader.frag"),shaderc_fragment_shader));
  int ref=armor?program(Files.readString(root.resolve("baseline.vert")),Files.readString(root.resolve("shader.frag"))):program("#version 330\nlayout(location=0) in vec3 Position;layout(location=2) in vec2 UV0;layout(std140) uniform Projection{mat4 ProjMat;};layout(std140) uniform DynamicTransforms{mat4 ModelViewMat;mat4 TextureMat;vec4 ColorModulator;vec3 ModelOffset;};out vec2 uv;void main(){gl_Position=ProjMat*ModelViewMat*vec4(Position,1);uv=UV0;}","#version 330\nuniform sampler2D Sampler0;in vec2 uv;out vec4 color;void main(){color=texture(Sampler0,uv);}");
  fbo=glGenFramebuffers();glBindFramebuffer(GL_FRAMEBUFFER,fbo);colorTarget=glGenTextures();glBindTexture(GL_TEXTURE_2D,colorTarget);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,W,H,0,GL_RGBA,GL_UNSIGNED_BYTE,(ByteBuffer)null);glFramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,colorTarget,0);depthTarget=glGenRenderbuffers();glBindRenderbuffer(GL_RENDERBUFFER,depthTarget);glRenderbufferStorage(GL_RENDERBUFFER,GL_DEPTH_COMPONENT24,W,H);glFramebufferRenderbuffer(GL_FRAMEBUFFER,GL_DEPTH_ATTACHMENT,GL_RENDERBUFFER,depthTarget);if(glCheckFramebufferStatus(GL_FRAMEBUFFER)!=GL_FRAMEBUFFER_COMPLETE)throw new Exception("FBO incomplete");glViewport(0,0,W,H);glEnable(GL_DEPTH_TEST);glDepthFunc(armor?GL_GREATER:GL_LESS);glDisable(GL_CULL_FACE);glDisable(GL_BLEND);glDisable(GL_DITHER);
  List<String> reports=new ArrayList<>();int failures=0;
  for(String line:Files.readAllLines(root.resolve("cases.txt"))){Path dir=Path.of(line);String[] m=Files.readString(dir.resolve("meta.txt")).trim().split(" ");int tw=Integer.parseInt(m[0]),th=Integer.parseInt(m[1]),rw=Integer.parseInt(m[2]),rh=Integer.parseInt(m[3]),count=Integer.parseInt(m[4]),base=Integer.parseInt(m[5]);float time=Float.parseFloat(m[6]);int stride=m.length>7?Integer.parseInt(m[7]):5;int tex=texture(dir.resolve("texture.rgba"),tw,th),rt=texture(dir.resolve("reference.rgba"),rw,rh);int[] mesh=geometry(dir.resolve("carrier.f32"),count,base,stride),nativeMesh=geometry(dir.resolve("reference.f32"),count,base,stride);uniforms(direct,time);byte[] a=draw(direct,tex,mesh);uniforms(ref,time);byte[] b=draw(ref,rt,nativeMesh);png(dir.resolve("direct.png"),a);png(dir.resolve("reference.png"),b);int area=0,missing=0,extra=0,rgb=0;long error=0;for(int i=0;i<a.length;i+=4){boolean aa=(a[i+3]&255)>0,bb=(b[i+3]&255)>0;if(bb)area++;if(bb&&!aa)missing++;if(aa&&!bb)extra++;if(aa&&bb){int d=0;for(int k=0;k<3;k++)d+=Math.abs((a[i+k]&255)-(b[i+k]&255));error+=d;if(d>6)rgb++;}}
   boolean pass=area>100&&(missing+extra)<=Math.max(10,area*.002)&&rgb<=Math.max(30,area*.005);if(!pass)failures++;String report=String.format(Locale.ROOT,"%s %s referencePixels=%d missing=%d extra=%d rgbMismatch=%d meanRGBError=%.5f",pass?"PASS":"FAIL",dir.getFileName(),area,missing,extra,rgb,(double)error/Math.max(1,area)/3);reports.add(report);System.out.println(report);glDeleteTextures(tex);glDeleteTextures(rt);for(int u:ubos)glDeleteBuffers(u);ubos.clear();for(int[] geo:new int[][]{mesh,nativeMesh}){glDeleteVertexArrays(geo[0]);glDeleteBuffers(geo[1]);glDeleteBuffers(geo[2]);}}
  reports.add("Synthetic raster only; no gameplay FPS or cross-vendor guarantee. Failures="+failures);Files.write(root.resolve("results.txt"),reports);glDeleteProgram(direct);glDeleteProgram(ref);GLFW.glfwDestroyWindow(win);GLFW.glfwTerminate();if(failures>0)System.exit(1);
 }
}
