// Real raster GLSL BVH selection versus an independent CPU triangle scan.
// Inputs are generated by bvh-gpu-test.mjs; no transform feedback is used.
#include <epoxy/egl.h>
#include <epoxy/gl.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define SIDE 16
typedef struct { double x,y,z; } V;
static V add(V a,V b){return(V){a.x+b.x,a.y+b.y,a.z+b.z};}
static V sub(V a,V b){return(V){a.x-b.x,a.y-b.y,a.z-b.z};}
static V mul(V a,double k){return(V){a.x*k,a.y*k,a.z*k};}
static V cross(V a,V b){return(V){a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static double dot(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static void die(const char*s){fprintf(stderr,"%s\n",s);exit(1);}
static unsigned char*read_file(const char*dir,const char*name,long*length){
  char file[4096];snprintf(file,sizeof file,"%s/%s",dir,name);FILE*f=fopen(file,"rb");
  if(!f){perror(file);exit(1);}fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);
  unsigned char*p=calloc((size_t)n+1,1);if(!p||fread(p,1,n,f)!=(size_t)n)die("read failed");
  fclose(f);if(length)*length=n;return p;
}
static GLuint shader(const char*dir,const char*name,GLenum type){
  char*s=(char*)read_file(dir,name,NULL);GLuint sh=glCreateShader(type);glShaderSource(sh,1,(const char**)&s,NULL);glCompileShader(sh);free(s);
  GLint ok;glGetShaderiv(sh,GL_COMPILE_STATUS,&ok);if(!ok){char log[16384];glGetShaderInfoLog(sh,sizeof log,NULL,log);fprintf(stderr,"%s\n",log);die("compile failed");}return sh;
}
static GLuint program(const char*dir,int zero){
  char name[64];snprintf(name,sizeof name,"trace%d.frag",zero);
  GLuint v=shader(dir,"fullscreen.vert",GL_VERTEX_SHADER),f=shader(dir,name,GL_FRAGMENT_SHADER),p=glCreateProgram();
  glAttachShader(p,v);glAttachShader(p,f);glLinkProgram(p);GLint ok;glGetProgramiv(p,GL_LINK_STATUS,&ok);
  if(!ok){char log[16384];glGetProgramInfoLog(p,sizeof log,NULL,log);fprintf(stderr,"%s\n",log);die("link failed");}
  glDeleteShader(v);glDeleteShader(f);return p;
}
static void init(void){
  PFNEGLGETPLATFORMDISPLAYEXTPROC g=(PFNEGLGETPLATFORMDISPLAYEXTPROC)eglGetProcAddress("eglGetPlatformDisplayEXT");
  EGLDisplay d=g?g(EGL_PLATFORM_SURFACELESS_MESA,EGL_DEFAULT_DISPLAY,NULL):eglGetDisplay(EGL_DEFAULT_DISPLAY);EGLint a,b;
  if(!eglInitialize(d,&a,&b)||!eglBindAPI(EGL_OPENGL_API))die("EGL init failed");
  const EGLint ca[]={EGL_SURFACE_TYPE,EGL_PBUFFER_BIT,EGL_RENDERABLE_TYPE,EGL_OPENGL_BIT,EGL_NONE};EGLConfig config;EGLint count;
  if(!eglChooseConfig(d,ca,&config,1,&count)||!count)die("EGL config failed");
  const EGLint xa[]={EGL_CONTEXT_MAJOR_VERSION,3,EGL_CONTEXT_MINOR_VERSION,3,EGL_CONTEXT_OPENGL_PROFILE_MASK,EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT,EGL_NONE};
  EGLContext ctx=eglCreateContext(d,config,EGL_NO_CONTEXT,xa);const EGLint sa[]={EGL_WIDTH,1,EGL_HEIGHT,1,EGL_NONE};
  EGLSurface s=eglCreatePbufferSurface(d,config,sa);
  if(ctx==EGL_NO_CONTEXT||s==EGL_NO_SURFACE||!eglMakeCurrent(d,s,s,ctx))die("GL3.3 context failed");
  printf("GL %s on %s\n",glGetString(GL_VERSION),glGetString(GL_RENDERER));fflush(stdout);
}
static int u24(const unsigned char*d,int p){return d[p*4]*65536+d[p*4+1]*256+d[p*4+2];}
static void identity(float m[16]){memset(m,0,16*sizeof(float));m[0]=m[5]=m[10]=m[15]=1;}
static V transform4(const float*m,V p){return(V){m[0]*p.x+m[4]*p.y+m[8]*p.z+m[12],m[1]*p.x+m[5]*p.y+m[9]*p.z+m[13],m[2]*p.x+m[6]*p.y+m[10]*p.z+m[14]};}
static double triangle(V o,V d,V a,V b,V c){
  V e1=sub(b,a),e2=sub(c,a),p=cross(d,e2);double det=dot(e1,p);if(fabs(det)<1e-13)return INFINITY;
  V t=sub(o,a);double u=dot(t,p)/det;if(u<0||u>1)return INFINITY;
  V q=cross(t,e1);double v=dot(d,q)/det;if(v<0||u+v>1)return INFINITY;
  double distance=dot(e2,q)/det;return distance>=0?distance:INFINITY;
}
static double face_hit(V o,V d,const V*p,int face){const V*v=p+face*4;return fmin(triangle(o,d,v[0],v[1],v[2]),triangle(o,d,v[2],v[3],v[0]));}
static V triangle_parameters(V o,V d,V a,V b,V c){
  V e1=sub(b,a),e2=sub(c,a),p=cross(d,e2),t=sub(o,a),q=cross(t,e1);double det=dot(e1,p);
  return(V){dot(t,p)/det,dot(d,q)/det,dot(e2,q)/det};
}
static double outside_distance(V uv,V a,V b,V c){
  V ab=sub(b,a),ac=sub(c,a),bc=sub(c,b);double area=sqrt(dot(cross(ab,ac),cross(ab,ac)));
  double h0=area/sqrt(dot(ac,ac)),h1=area/sqrt(dot(ab,ab)),h2=area/sqrt(dot(bc,bc));
  return fmax(0,fmax(-uv.x*h0,fmax(-uv.y*h1,(uv.x+uv.y-1)*h2)));
}
static V sample(const V*p,int vertices,int frames,int v,int frame,int easing,double t){
  V a=p[frame*vertices+v],b=p[((frame+1)%frames)*vertices+v];if(easing==0||frames==1)return a;
  if(easing==2)t=t<.5?4*t*t*t:1-pow(-2*t+2,3)*.5;
  if(easing<3)return add(mul(a,1-t),mul(b,t));
  V c=p[((frame+2)%frames)*vertices+v],d=p[((frame+3)%frames)*vertices+v];double s=1-t;
  // Existing bezier(a,b,c,d,t) traverses the middle segment b -> c.
  V c1=add(b,mul(sub(c,a),1./6)),c2=sub(c,mul(sub(d,b),1./6));
  return add(add(mul(b,s*s*s),mul(c1,3*s*s*t)),add(mul(c2,3*s*t*t),mul(c,t*t*t)));
}

static V rotate(float angle,V p){
  double c=cosf(angle),s=sinf(angle);return(V){c*p.x+s*p.z,p.y,-s*p.x+c*p.z};
}
static V model_direction(float angle,int reflected,V p){if(reflected)p.x=-p.x;return rotate(angle,p);}
int main(int argc,char**argv){
 if(argc<2||argc>3||(argc==3&&strcmp(argv[2],"--native-part")))die("Usage: armor-bvh-test PREPARED_DIRECTORY [--native-part]");
 int native_part=argc==3;
 const char*dir=argv[1];init();
 char*size=(char*)read_file(dir,"size.txt",NULL);int width,height;if(sscanf(size,"%d %d",&width,&height)!=2)die("Bad dimensions");free(size);
 long length;unsigned char*raw=read_file(dir,"texture.rgba",&length);if(length!=(long)width*height*4)die("Bad texture length");
 int vertices=raw[8]*16777216+raw[9]*65536+raw[10]*256+raw[29],frames=u24(raw,3);if(frames<1)frames=1;
 int faces=vertices/4,ph=raw[20]*256+raw[21],uh=raw[22]*256+raw[30],th=raw[6]*256+raw[28],nt=raw[15]?raw[15]:1;
 int pr=2+(faces+width-1)/width+th*nt,ir=pr+ph+uh;
 int segmentRow=u24(raw,30),declaredEasing=(raw[19]>>4)&3,inner=raw[27*4+2]!=0,duration=u24(raw,4);
 if(duration<1)duration=1;
 V*source=malloc((size_t)vertices*frames*sizeof(V)),*posed=malloc((size_t)vertices*sizeof(V));if(!source||!posed)die("allocation");
 for(int i=0;i<vertices*frames;i++){int p=u24(raw,ir*width+i*2)*3+pr*width;source[i]=(V){u24(raw,p)/65536.-128,u24(raw,p+1)/65536.-128,u24(raw,p+2)/65536.-128};}
 GLuint tex,target,fbo,vao;glGenTextures(1,&tex);glBindTexture(GL_TEXTURE_2D,tex);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,width,height,0,GL_RGBA,GL_UNSIGNED_BYTE,raw);
 glGenTextures(1,&target);glBindTexture(GL_TEXTURE_2D,target);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA32F,SIDE,SIDE,0,GL_RGBA,GL_FLOAT,NULL);glGenFramebuffers(1,&fbo);glBindFramebuffer(GL_FRAMEBUFFER,fbo);glFramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,target,0);if(glCheckFramebufferStatus(GL_FRAMEBUFFER)!=GL_FRAMEBUFFER_COMPLETE)die("FBO");
 glGenVertexArrays(1,&vao);glBindVertexArray(vao);glBindTexture(GL_TEXTURE_2D,tex);glViewport(0,0,SIDE,SIDE);
 float pixels[SIDE*SIDE*4];unsigned cases=0,failed=0,hits=0,roundoff=0;double maxError=0,maxCenter=0,maxRoundoff=0;
 for(int zero=0;zero<2;zero++){
  GLuint prog=program(dir,zero);glUseProgram(prog);glUniform1i(glGetUniformLocation(prog,"Sampler0"),0);glUniform2f(glGetUniformLocation(prog,"Resolution"),SIDE,SIDE);
  for(int partIndex=0;partIndex<(native_part?1:3);partIndex++){
   int part=native_part?raw[27*4]:(int[]){0,2,3}[partIndex],left=part==3;
   for(int ortho=0;ortho<2;ortho++)for(int shape=0;shape<3;shape++)for(int segment=0;segment<(segmentRow?2:1);segment++)for(int ec=0;ec<(segment?1:4);ec++)for(int frame=0;frame<frames;frame++){
    int easing=segment?declaredEasing:ec;float fraction=(float)(.13+.21*(frame%4));
    float scale=(float[]){.75f,1.4f,80.f}[shape],angle=.23f*(shape+1);int reflected=shape==2;
    float projection[16]={0},view[16];identity(view);const float near=.1f,far=2000.f,focal=1.7f,half=3.4f*scale;
    if(ortho){projection[0]=projection[5]=1/half;projection[10]=(zero?1.f:2.f)/(far-near);projection[14]=(zero?far:far+near)/(far-near);projection[15]=1;}
    else{projection[0]=projection[5]=focal;projection[10]=(zero?near:far+near)/(far-near);projection[11]=-1;projection[14]=(zero?1.f:2.f)*far*near/(far-near);}
    view[13]=-.25f*scale;view[14]=-7.f*scale;
    V anchor={.12f,-.07f,.16f},offset=part==0?(V){.2925,-.785,-.175}:part==2?(V){.2375,-.66,-.175}:(V){.2375,.16,-.175};
    if(part==0&&inner)offset=add(offset,(V){-.0293,.0293,.0293});
    double inflation=inner?.5:1,bodyWidth=part==0?8:4;
    float h=(12+2*inflation)*.9235f/16.f,w=(bodyWidth+2*inflation)*.9235f/16.f;
    V base[4]={{w,-h,0},{0,-h,0},{0,0,0},{w,0,0}};
    float carrier[12];for(int i=0;i<4;i++){
     V p=add(anchor,mul(model_direction(angle,reflected,base[left?3-i:i]),scale));
     carrier[i*3]=p.x;carrier[i*3+1]=p.y;carrier[i*3+2]=p.z;
    }
    V normal=rotate(angle,(V){0,0,-1});
    for(int i=0;i<vertices;i++){
     int sourceIndex=left?(i/4)*4+3-i%4:i;
     V p=sample(source,vertices,frames,sourceIndex,frame,easing,fraction);p.y+=.5;if(left)p.x=-p.x;p=sub(p,offset);
     p=(V){-p.x,left?p.y:-p.y,p.z};
     posed[i]=transform4(view,add(anchor,mul(model_direction(angle,reflected,p),scale)));
    }
    unsigned char *header=malloc((size_t)width*4);memcpy(header,raw,(size_t)width*4);header[8*4+2]=part;header[27*4]=part;header[19]=(header[19]&15)|64|(easing<<4);
    if(!segment)header[30*4]=header[30*4+1]=header[30*4+2]=0;
    glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width,1,GL_RGBA,GL_UNSIGNED_BYTE,header);free(header);
    glUniformMatrix4fv(glGetUniformLocation(prog,"ProjMat"),1,GL_FALSE,projection);glUniformMatrix4fv(glGetUniformLocation(prog,"ModelViewMat"),1,GL_FALSE,view);
    glUniform3fv(glGetUniformLocation(prog,"oc_carrier_positions"),4,carrier);glUniform3f(glGetUniformLocation(prog,"oc_source_normal"),normal.x,normal.y,normal.z);
    glUniform4f(glGetUniformLocation(prog,"oc_parameters"),0,0,part|(3<<3)|(inner?64:0),5);
    glUniform4f(glGetUniformLocation(prog,"oc_decoded_uv01"),frame,easing,fraction,frames);
    glUniform1f(glGetUniformLocation(prog,"GameTime"),(frame+fraction)*(float)duration/frames/24000.f);
    glDrawArrays(GL_TRIANGLES,0,3);glReadPixels(0,0,SIDE,SIDE,GL_RGBA,GL_FLOAT,pixels);
    if(glGetError()!=GL_NO_ERROR)die("GL error");
    for(int y=0;y<SIDE;y++)for(int x=0;x<SIDE;x++){
     double sx=(x+.5)*2/SIDE-1,sy=(y+.5)*2/SIDE-1;
     V o=ortho?(V){sx*half,sy*half,-near}:(V){sx*near/focal,sy*near/focal,-near};V d=ortho?(V){0,0,-1}:(V){sx/focal,sy/focal,-1};
     double nearest=INFINITY;int nearestFace=-1;for(int face=0;face<faces;face++){double t=face_hit(o,d,posed,face);if(t<=nearest){nearest=t;nearestFace=face;}}
     float *pixel=pixels+(y*SIDE+x)*4;int got=(int)lroundf(pixel[0])-1;double selected=got>=0&&got<faces?face_hit(o,d,posed,got):INFINITY;
     if(isfinite(nearest))hits++;
     double delta=fabs(selected-nearest);if(isfinite(delta))maxError=fmax(maxError,delta);
     double tolerance=2e-4*fmax(scale,1.f);
     int bad=isfinite(nearest)!=isfinite(selected)||(isfinite(nearest)&&delta>tolerance);
     if(bad&&isfinite(nearest)&&got>=0&&got<faces){
      const V*v=posed+got*4;V a=triangle_parameters(o,d,v[0],v[1],v[2]),b=triangle_parameters(o,d,v[2],v[3],v[0]);
      double ea=fabs(a.z-nearest)<=tolerance?outside_distance(a,v[0],v[1],v[2]):INFINITY;
      double eb=fabs(b.z-nearest)<=tolerance?outside_distance(b,v[2],v[3],v[0]):INFINITY;double edge=fmin(ea,eb);
      if(isfinite(edge)&&edge<=2e-5*fmax(scale,1.f)){roundoff++;maxRoundoff=fmax(maxRoundoff,edge);bad=0;}
     }
     if(got>=0&&got<faces){
      V center={0,0,0};for(int i=0;i<4;i++)center=add(center,mul(posed[got*4+i],.25));
      double error=fmax(fabs(center.x-pixel[1]),fmax(fabs(center.y-pixel[2]),fabs(center.z-pixel[3])));maxCenter=fmax(maxCenter,error);
      if(error>tolerance)bad=1;
     }
     if(bad){if(failed<12)fprintf(stderr,"FAIL case=%u depth=%d part=%d ortho=%d shape=%d segment=%d easing=%d frame=%d pixel=%d,%d selected=%d reference=%d distance=%.9g/%.9g centermax=%.9g\n",cases,zero,part,ortho,shape,segment,easing,frame,x,y,got,nearestFace,selected,nearest,maxCenter);failed++;}
    }
    cases++;
   }
   printf("Depth=%d part=%d complete: %u draws, %u failures\n",zero,part,cases,failed);fflush(stdout);
  }
  glDeleteProgram(prog);
 }
 printf("%u draws / %u pixels / %u hits; %u failures; %u bounded edge-roundoff selections (maxoutside %.9g); maxselecteddistanceerror %.9g; maxdecodedcentererror %.9g\n",cases,cases*SIDE*SIDE,hits,failed,roundoff,maxRoundoff,maxError,maxCenter);
 free(raw);free(source);free(posed);return failed?2:0;
}
